services:
  - name: deploy and population
    buildCommand: npm install && npx prisma migrate deploy
    startCommand: npm start
    env: 
      - key: DATABASE_URL
        fromDatabase:
          name: games-db 
    postDeploy: npm run seed